// GENERATED by tools/pull_agile_actuators.py — do not edit.
// Source: WBC-AGILE G1_29DOF_DELAYED_DC_MOTOR + Velocity-G1-History task cfg.
// (name, kp, kd, effort, vel_limit, armature, saturation_effort, default_pos)
pub const AGILE_ACTION_SCALE: f32 = 0.5;
pub const AGILE_G1_ACTUATORS: [(&str, f32, f32, f32, f32, f32, f32, f32); 12] = [
    ("left_hip_pitch_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, -0.1),
    ("left_hip_roll_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, 0.0),
    ("left_hip_yaw_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, 0.0),
    ("left_knee_joint", 200.0, 5.0, 139.0, 20.0, 0.02, 180.0, 0.3),
    ("left_ankle_pitch_joint", 20.0, 0.2, 50.0, 37.0, 0.02, 80.0, -0.2),
    ("left_ankle_roll_joint", 20.0, 0.1, 50.0, 37.0, 0.02, 80.0, 0.0),
    ("right_hip_pitch_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, -0.1),
    ("right_hip_roll_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, 0.0),
    ("right_hip_yaw_joint", 100.0, 2.5, 88.0, 32.0, 0.02, 180.0, 0.0),
    ("right_knee_joint", 200.0, 5.0, 139.0, 20.0, 0.02, 180.0, 0.3),
    ("right_ankle_pitch_joint", 20.0, 0.2, 50.0, 37.0, 0.02, 80.0, -0.2),
    ("right_ankle_roll_joint", 20.0, 0.1, 50.0, 37.0, 0.02, 80.0, 0.0),
];
