models:
  Velocity-G1-History-v0:
    inputs:
      - name: root_link_quat_w
        dtype: float32
        shape: [1, 4]
        type: tensor
        kind: state/body/rotation
        element_names: [[pelvis], [w, x, y, z]]
      - name: root_ang_vel_b
        dtype: float32
        shape: [1, 3]
        type: tensor
        kind: state/body/angular_velocity
        element_names: [[pelvis], [x, y, z]]
      - name: velocity_commands
        dtype: float32
        shape: [1, 3]
        type: tensor
        kind: velocity_command
        element_names: [[lin_x, lin_y, ang_z]]
      - name: joint_pos
        dtype: float32
        shape: [1, 29]
        type: tensor
        kind: state/joint/position
        element_names: [[left_hip_pitch_joint, right_hip_pitch_joint, waist_yaw_joint, left_hip_roll_joint, right_hip_roll_joint, waist_roll_joint, left_hip_yaw_joint, right_hip_yaw_joint, waist_pitch_joint, left_knee_joint, right_knee_joint, left_shoulder_pitch_joint, right_shoulder_pitch_joint, left_ankle_pitch_joint, right_ankle_pitch_joint, left_shoulder_roll_joint, right_shoulder_roll_joint, left_ankle_roll_joint, right_ankle_roll_joint, left_shoulder_yaw_joint, right_shoulder_yaw_joint, left_elbow_joint, right_elbow_joint, left_wrist_roll_joint, right_wrist_roll_joint, left_wrist_pitch_joint, right_wrist_pitch_joint, left_wrist_yaw_joint, right_wrist_yaw_joint]]
      - name: joint_vel
        dtype: float32
        shape: [1, 29]
        type: tensor
        kind: state/joint/velocity
        element_names: [[left_hip_pitch_joint, right_hip_pitch_joint, waist_yaw_joint, left_hip_roll_joint, right_hip_roll_joint, waist_roll_joint, left_hip_yaw_joint, right_hip_yaw_joint, waist_pitch_joint, left_knee_joint, right_knee_joint, left_shoulder_pitch_joint, right_shoulder_pitch_joint, left_ankle_pitch_joint, right_ankle_pitch_joint, left_shoulder_roll_joint, right_shoulder_roll_joint, left_ankle_roll_joint, right_ankle_roll_joint, left_shoulder_yaw_joint, right_shoulder_yaw_joint, left_elbow_joint, right_elbow_joint, left_wrist_roll_joint, right_wrist_roll_joint, left_wrist_pitch_joint, right_wrist_pitch_joint, left_wrist_yaw_joint, right_wrist_yaw_joint]]
      - name: last_actions
        dtype: float32
        shape: [1, 14]
        type: tensor
        is_state: true
      - name: base_ang_vel_history
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: projected_gravity_history
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: velocity_commands_history
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: controlled_joint_pos_history
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
      - name: controlled_joint_vel_history
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
      - name: actions_history
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
    outputs:
      - name: action_joint_pos
        dtype: float32
        shape: [1, 14]
        type: tensor
        kind: target/joint/position
        element_names: [[left_hip_pitch_joint, right_hip_pitch_joint, left_hip_roll_joint, right_hip_roll_joint, waist_roll_joint, left_hip_yaw_joint, right_hip_yaw_joint, waist_pitch_joint, left_knee_joint, right_knee_joint, left_ankle_pitch_joint, right_ankle_pitch_joint, left_ankle_roll_joint, right_ankle_roll_joint]]
      - name: action_joint_pos_kp_gains
        dtype: float32
        shape: [1, 14]
        type: tensor
        kind: kp
        element_names: [[left_hip_pitch_joint, right_hip_pitch_joint, left_hip_roll_joint, right_hip_roll_joint, waist_roll_joint, left_hip_yaw_joint, right_hip_yaw_joint, waist_pitch_joint, left_knee_joint, right_knee_joint, left_ankle_pitch_joint, right_ankle_pitch_joint, left_ankle_roll_joint, right_ankle_roll_joint]]
      - name: action_joint_pos_kd_gains
        dtype: float32
        shape: [1, 14]
        type: tensor
        kind: kd
        element_names: [[left_hip_pitch_joint, right_hip_pitch_joint, left_hip_roll_joint, right_hip_roll_joint, waist_roll_joint, left_hip_yaw_joint, right_hip_yaw_joint, waist_pitch_joint, left_knee_joint, right_knee_joint, left_ankle_pitch_joint, right_ankle_pitch_joint, left_ankle_roll_joint, right_ankle_roll_joint]]
      - name: last_actions_out
        dtype: float32
        shape: [1, 14]
        type: tensor
        is_state: true
      - name: base_ang_vel_history_out
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: projected_gravity_history_out
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: velocity_commands_history_out
        dtype: float32
        shape: [1, 5, 3]
        type: tensor
        is_state: true
      - name: controlled_joint_pos_history_out
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
      - name: controlled_joint_vel_history_out
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
      - name: actions_history_out
        dtype: float32
        shape: [1, 5, 14]
        type: tensor
        is_state: true
    parameters:
      model_path: unitree_g1_velocity_e2e.onnx
      md5sum: 9faadaf1eea9c8888e60144ef87e9dd3
      sha256sum: 8995f2462ba2d0d83afe08905148f6373990d50018610663a539225d268ef33b
      device: cuda
      backend: triton
pipeline:
  data_flow: {}
  feedback_connections:
    Velocity-G1-History-v0/actions_history_out: [Velocity-G1-History-v0/actions_history]
    Velocity-G1-History-v0/base_ang_vel_history_out: [Velocity-G1-History-v0/base_ang_vel_history]
    Velocity-G1-History-v0/controlled_joint_pos_history_out: [Velocity-G1-History-v0/controlled_joint_pos_history]
    Velocity-G1-History-v0/controlled_joint_vel_history_out: [Velocity-G1-History-v0/controlled_joint_vel_history]
    Velocity-G1-History-v0/last_actions_out: [Velocity-G1-History-v0/last_actions]
    Velocity-G1-History-v0/projected_gravity_history_out: [Velocity-G1-History-v0/projected_gravity_history]
    Velocity-G1-History-v0/velocity_commands_history_out: [Velocity-G1-History-v0/velocity_commands_history]
  inputs:
    Velocity-G1-History-v0: [root_link_quat_w, root_ang_vel_b, velocity_commands, joint_pos, joint_vel]
  outputs:
    Velocity-G1-History-v0: [action_joint_pos, action_joint_pos_kp_gains, action_joint_pos_kd_gains]
system information:
  cuda version: '12.8'
  os: Linux
  python version: 3.11.14
  torch version: 2.7.0+cu128
semantic:
  observations:
    - name: base_ang_vel
      mapping:
        - root_link_quat_w
        - root_ang_vel_b
      units: rad/s
    - name: projected_gravity
      mapping:
        - root_link_quat_w
      units: m/s^2
    - name: generated_commands
      mapping:
        - velocity_commands
    - name: joint_pos_rel
      mapping:
        - joint_pos
      joint_names:
        - left_hip_pitch_joint
        - right_hip_pitch_joint
        - left_hip_roll_joint
        - right_hip_roll_joint
        - waist_roll_joint
        - left_hip_yaw_joint
        - right_hip_yaw_joint
        - waist_pitch_joint
        - left_knee_joint
        - right_knee_joint
        - left_ankle_pitch_joint
        - right_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_ankle_roll_joint
      units: rad
    - name: joint_vel_rel
      mapping:
        - joint_vel
      joint_names:
        - left_hip_pitch_joint
        - right_hip_pitch_joint
        - left_hip_roll_joint
        - right_hip_roll_joint
        - waist_roll_joint
        - left_hip_yaw_joint
        - right_hip_yaw_joint
        - waist_pitch_joint
        - left_knee_joint
        - right_knee_joint
        - left_ankle_pitch_joint
        - right_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_ankle_roll_joint
      units: rad/s
    - name: last_action
      mapping:
        - last_actions
  actions:
    - name: joint_position_action
      mapping:
        - joint_pos
      class_type: JointPositionAction
      joint_names:
        - left_hip_pitch_joint
        - right_hip_pitch_joint
        - left_hip_roll_joint
        - right_hip_roll_joint
        - waist_roll_joint
        - left_hip_yaw_joint
        - right_hip_yaw_joint
        - waist_pitch_joint
        - left_knee_joint
        - right_knee_joint
        - left_ankle_pitch_joint
        - right_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_ankle_roll_joint
    - name: random_position_action
      mapping:
        - random_pos
      class_type: RandomPositionAction
      joint_names:
        - left_shoulder_pitch_joint
        - right_shoulder_pitch_joint
        - left_shoulder_roll_joint
        - right_shoulder_roll_joint
        - left_shoulder_yaw_joint
        - right_shoulder_yaw_joint
        - left_elbow_joint
        - right_elbow_joint
        - left_wrist_roll_joint
        - right_wrist_roll_joint
        - left_wrist_pitch_joint
        - right_wrist_pitch_joint
        - left_wrist_yaw_joint
        - right_wrist_yaw_joint
  scene:
    physics_dt: 0.005
    dt: 0.02
    decimation: 4
  history:
    terms:
      - name: base_ang_vel
        length: 5
        dim: 3
      - name: projected_gravity
        length: 5
        dim: 3
      - name: velocity_commands
        length: 5
        dim: 3
      - name: controlled_joint_pos
        length: 5
        dim: 14
      - name: controlled_joint_vel
        length: 5
        dim: 14
      - name: actions
        length: 5
        dim: 14
    layout: per_term
