//! The **Unitree G1** humanoid, as a legs-only 12-DOF walking platform.
//!
//! Model: `assets/robots/unitree_g1_12dof.xml`, generated by
//! `tools/convert_unitree_biped.py` from the OFFICIAL legs-only model
//! (`unitree_rl_gym/resources/robots/g1_description/g1_12dof.{urdf,xml}`, also
//! mirrored into the `unitree_ros` checkout) — the pelvis carries the fused
//! upper-body mass (17.73 of 32.11 kg), and the converter normalizes every
//! hinge axis to local +Z (zealot's joint-builder convention; the G1 model uses
//! X for roll, Y for pitch, Z for yaw).
//!
//! Numbers and their provenance:
//!
//! - **PD gains / action scale / default pose**: unitree_rl_gym `G1RoughCfg`
//!   (`legged_gym/envs/g1/g1_config.py`) — the config Unitree trains and
//!   deploys their public G1 walking policy with: kp hip 100 / knee 150 /
//!   ankle 40, kd 2/2/2/4/2, `action_scale` 0.25, home pose hip_pitch −0.1,
//!   knee 0.3, ankle_pitch −0.2.
//! - **Effort / velocity / position limits**: the `g1_12dof.urdf` `<limit>`
//!   elements (hip pitch/yaw 88 N·m @ 32 rad/s, hip roll & knee 139 N·m @ 20,
//!   ankles 50 N·m @ 37).
//! - **Armature / passive damping**: the official MJCF's joint defaults
//!   (`armature="0.01"`, `damping="0.001"`); no `frictionloss` in the model.
//! - **Heights**: measured by the converter's FK — straight-leg pelvis 0.792 m
//!   (spawn), home-pose pelvis 0.784 m; the reward target uses unitree_rl_gym's
//!   official `base_height_target` 0.78.
//!
//! ## Joint ordering
//!
//! Canonical order is unitree_rl_gym's DOF order (left leg root→foot, then
//! right leg), so observations/actions — and an eventual ONNX export — line up
//! with Unitree's deployment convention.

use super::{JointSpec, RobotSpec, NUM_JOINTS};

/// Canonical policy joint order (see module docs).
pub const JOINT_NAMES: [&str; NUM_JOINTS] = [
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
];

/// Per-joint spec. `pos_limit` is per-JOINT (the hip-roll range is
/// left/right-asymmetric), everything else is per-family.
const fn joint(name: &'static str, default_pos: f32, pos_limit: (f32, f32)) -> JointSpec {
    // (kp, kd, effort, vel) per family — see module docs for provenance.
    let (kp, kd, effort, vel) = if contains(name, "hip_roll") {
        (100.0, 2.0, 139.0, 20.0)
    } else if contains(name, "hip") {
        (100.0, 2.0, 88.0, 32.0) // hip_pitch / hip_yaw
    } else if contains(name, "knee") {
        (150.0, 4.0, 139.0, 20.0)
    } else {
        (40.0, 2.0, 50.0, 37.0) // ankle_pitch / ankle_roll
    };
    JointSpec {
        name,
        kp,
        kd,
        effort_limit: effort,
        vel_limit: vel,
        action_scale: 0.25,
        default_pos,
        pos_limit,
        armature: 0.01,
        damping: 0.001,
        frictionloss: 0.0,
    }
}

/// `const`-friendly substring search (ASCII).
const fn contains(s: &str, needle: &str) -> bool {
    let (s, n) = (s.as_bytes(), needle.as_bytes());
    if n.len() > s.len() {
        return false;
    }
    let mut i = 0;
    while i + n.len() <= s.len() {
        let mut j = 0;
        while j < n.len() && s[i + j] == n[j] {
            j += 1;
        }
        if j == n.len() {
            return true;
        }
        i += 1;
    }
    false
}

/// The Unitree G1 (legs-only, 12 DOF) spec.
pub const fn unitree_g1() -> RobotSpec {
    let joints = [
        joint(JOINT_NAMES[0], -0.1, (-2.5307, 2.8798)), // left_hip_pitch
        joint(JOINT_NAMES[1], 0.0, (-0.5236, 2.9671)),  // left_hip_roll
        joint(JOINT_NAMES[2], 0.0, (-2.7576, 2.7576)),  // left_hip_yaw
        joint(JOINT_NAMES[3], 0.3, (-0.087267, 2.8798)), // left_knee
        joint(JOINT_NAMES[4], -0.2, (-0.87267, 0.5236)), // left_ankle_pitch
        joint(JOINT_NAMES[5], 0.0, (-0.2618, 0.2618)),  // left_ankle_roll
        joint(JOINT_NAMES[6], -0.1, (-2.5307, 2.8798)), // right_hip_pitch
        joint(JOINT_NAMES[7], 0.0, (-2.9671, 0.5236)),  // right_hip_roll (mirrored range)
        joint(JOINT_NAMES[8], 0.0, (-2.7576, 2.7576)),  // right_hip_yaw
        joint(JOINT_NAMES[9], 0.3, (-0.087267, 2.8798)), // right_knee
        joint(JOINT_NAMES[10], -0.2, (-0.87267, 0.5236)), // right_ankle_pitch
        joint(JOINT_NAMES[11], 0.0, (-0.2618, 0.2618)), // right_ankle_roll
    ];
    RobotSpec {
        name: "unitree_g1",
        joints,
        base_link: "pelvis",
        // G1 chain: knee → ankle_pitch → ankle_roll; the ankle_roll link IS the
        // foot (it carries the sole collision capsules).
        foot_links: ["left_ankle_roll_link", "right_ankle_roll_link"],
        // The converter normalizes the ankle-roll hinge (X) to local +Z, which
        // maps the foot's forward (+X in the source model) to local +Z.
        foot_forward_local: [0.0, 0.0, 1.0],
        foot_contact_z: 0.05, // foot origin sits 0.035 m above the sole
        base_height: 0.78,    // unitree_rl_gym base_height_target (FK: 0.784)
        spawn_z: 0.792,       // converter FK: straight-leg sole-on-ground
        min_base_height: 0.45,
        total_mass: 32.11,
        mjcf_rel_path: "Documents/work/zealot/assets/robots/unitree_g1_12dof.xml",
        urdf_rel_path: "Documents/work/unitree_ros/robots/g1_description/g1_12dof.urdf",
        // Canonical order is left leg [0..6), right leg [6..12): mirror swaps
        // the halves; pitch/knee mirror equal, roll/yaw mirror opposite.
        mirror: [6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5],
        mirror_sign: [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0],
        hip_yawroll: [1, 2, 7, 8], // left/right hip_roll + hip_yaw
        // Only the feet may touch the ground; hips + knee(shin) links must not.
        // ("ankle" is excluded — those links legitimately sit just above the sole.)
        illegal_ground_fragments: &["hip", "knee"],
        // Feet, shins, thighs (the long thigh body hangs off hip_yaw on the G1).
        self_collision_pairs: &[
            ("right_ankle_roll_link", "left_ankle_roll_link"),
            ("right_knee_link", "left_knee_link"),
            ("right_hip_yaw_link", "left_hip_yaw_link"),
        ],
        held_joints: &[],
    }
}

/// [`unitree_g1`] with **WBC-AGILE's actuator parametrization** instead of
/// unitree_rl_gym's — for like-for-like training A/Bs against NVIDIA's
/// pipeline. Sourced from AGILE's `G1_29DOF_DELAYED_DC_MOTOR` +
/// `Velocity-G1-History` task cfg (regenerate the pinned table with
/// `tools/pull_agile_actuators.py`; the `agile_actuator_parity` test asserts
/// this spec matches it). Deltas vs [`unitree_g1`]: knee kp 150→200, ankle kp
/// 40→20, kd 2/4/2 → 2.5/5/0.2 (ankle_roll 0.1), armature 0.01→0.02,
/// hip_roll effort 139@20 → 88@32, action_scale 0.25→0.5. NOT yet modeled:
/// AGILE's DC torque-speed saturation (needs the nexus kernel change).
pub const fn unitree_g1_agile() -> RobotSpec {
    let mut spec = unitree_g1();
    spec.name = "unitree_g1_agile";
    let mut i = 0;
    while i < NUM_JOINTS {
        let j = &mut spec.joints[i];
        let name = j.name;
        if contains(name, "hip") {
            // All three hip families: kp 100 (same), kd 2.5, 88 N·m @ 32 rad/s
            // (AGILE bins hip_roll with the other hips, unlike the URDF).
            j.kd = 2.5;
            j.effort_limit = 88.0;
            j.vel_limit = 32.0;
        } else if contains(name, "knee") {
            j.kp = 200.0;
            j.kd = 5.0;
        } else {
            // ankles: soft position gain, near-zero damping.
            j.kp = 20.0;
            j.kd = if contains(name, "ankle_roll") { 0.1 } else { 0.2 };
        }
        j.armature = 0.02;
        j.action_scale = 0.5;
        i += 1;
    }
    spec
}

/// The Unitree G1 **rev 1.0 full body** (29-DOF model, 25 live joints): the
/// same 12 leg actions as [`unitree_g1`], but the waist (3), shoulders (3×2),
/// elbows and wrist rolls are REAL PD-held joints instead of mass welded into
/// the pelvis — the arms swing, react to pushes, and load the balance exactly
/// as on hardware. This is the GR00T/HOVER-style *body*; the action space
/// stays legs-only (Unitree's own deployable walking convention).
///
/// Model: `assets/robots/unitree_g1_29dof.xml`, generated from the official
/// `g1_29dof_rev_1_0.xml` with ONLY the four 5 N·m wrist pitch/yaw toy joints
/// welded away — nexus's GPU multibody caps at `MAX_MB_DOFS = 32` (one warp
/// lane per mass-matrix column), and 6 root + 25 hinges = 31 fits while the
/// full 35 does not.
///
/// Leg gains/limits are identical to [`unitree_g1`] (the rev 1.0 leg ranges
/// match the 12-DOF model's). `held_joints` gains hold the upper body at the
/// rest pose: waist like a hip (kp 100), arms kp 40 / kd 1 — holding gains,
/// not deployment sysid. Efforts are the model's actuator limits (waist yaw
/// 88 / waist roll+pitch 50 / arm joints 25 N·m).
pub const fn unitree_g1_29dof() -> RobotSpec {
    let mut spec = unitree_g1();
    spec.name = "unitree_g1_29dof";
    spec.mjcf_rel_path = "Documents/work/zealot/assets/robots/unitree_g1_29dof.xml";
    spec.urdf_rel_path = "Documents/work/unitree_ros/robots/g1_description/g1_29dof_rev_1_0.urdf";
    spec.total_mass = 33.34;
    // A fallen robot contacts the ground with its (collider-less) upper body —
    // count torso/waist/arm links as illegal ground contact alongside hips/knees.
    spec.illegal_ground_fragments = &["hip", "knee", "torso", "waist", "shoulder", "elbow", "wrist"];
    spec.held_joints = &[
        ("waist_yaw", 100.0, 2.0, 88.0),
        ("waist", 100.0, 2.0, 50.0), // waist_roll / waist_pitch
        ("shoulder", 40.0, 1.0, 25.0),
        ("elbow", 40.0, 1.0, 25.0),
        ("wrist", 40.0, 1.0, 25.0), // wrist_roll (pitch/yaw are welded)
    ];
    spec
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gains_match_unitree_rl_gym() {
        let r = unitree_g1();
        let by = |name: &str| r.joints.iter().find(|j| j.name == name).copied().unwrap();
        assert_eq!(by("left_hip_pitch_joint").kp, 100.0);
        assert_eq!(by("right_knee_joint").kp, 150.0);
        assert_eq!(by("left_ankle_roll_joint").kp, 40.0);
        assert_eq!(by("right_knee_joint").kd, 4.0);
        assert_eq!(by("left_hip_roll_joint").effort_limit, 139.0);
        assert_eq!(by("left_hip_yaw_joint").effort_limit, 88.0);
        assert_eq!(by("right_ankle_pitch_joint").effort_limit, 50.0);
        assert_eq!(by("left_knee_joint").default_pos, 0.3);
        assert_eq!(by("left_knee_joint").action_scale, 0.25);
    }

    #[test]
    fn hip_roll_ranges_mirror() {
        let r = unitree_g1();
        let l = r.joints[1].pos_limit;
        let rr = r.joints[7].pos_limit;
        assert_eq!(l, (-0.5236, 2.9671));
        assert_eq!(rr, (-2.9671, 0.5236));
    }
}
