//! The **Unitree H2 Plus** full-size humanoid (~1.8 m), as a legs-only 12-DOF
//! walking platform.
//!
//! Model: `assets/robots/unitree_h2_plus_12dof.xml`, generated by
//! `tools/convert_unitree_biped.py` from the official
//! `unitree_ros/robots/h2_plus/H2_Plus.urdf`: the waist (3), head (2), arms
//! (2×7) and hands (2×19) are welded into the pelvis (MuJoCo `fusestatic`, so
//! mass + inertia compose exactly — 77.24 kg total, vs 32.1 kg for the G1),
//! and every hinge axis is normalized to local +Z.
//!
//! Numbers and their provenance:
//!
//! - **Effort / velocity / position limits**: the URDF `<limit>` elements
//!   (hips & knee 360 N·m @ 20 rad/s; ankle pitch 66.88 N·m @ 28.6; ankle roll
//!   only 19 N·m @ 100.7 — a fragile roll motor, lerobot-ankle-style).
//! - **PD gains**: NO official RL config exists for the H2/H2 Plus (as of
//!   2026-07), so these are the unitree_rl_gym G1 gains mass-scaled by
//!   77.24/32.11 ≈ 2.4× on kp (√2.4 ≈ 1.55× on kd, keeping the damping ratio):
//!   hips 240/3, knee 360/6, ankle pitch 60/3 — except the 19 N·m ankle roll,
//!   which keeps the G1's 40/2 (a stiffer kp would just bang-bang against the
//!   tiny torque clamp — see the lerobot ankle rationale). Treat as a starting
//!   point for tuning, not sysid truth.
//! - **Armature**: not published; hips/knee get 0.05 (large rotors), ankles
//!   0.01 (G1-class). Also a tuning starting point.
//! - **Default pose**: the G1's bent-knee home (hip_pitch −0.1, knee 0.3,
//!   ankle_pitch −0.2) — proportions are close enough that the same crouch
//!   works, giving base height 1.032 m (converter FK).
//! - **Heights**: converter FK — straight-leg pelvis 1.039 m (spawn),
//!   home-pose pelvis 1.032 m (reward target).
//!
//! ## Joint ordering
//!
//! Same canonical convention as the G1 (left leg root→foot, then right leg).
//! NOTE the H2's ankle chain is roll-THEN-pitch (knee → ankle_roll →
//! ankle_pitch), the reverse of the G1 — so the FOOT link is
//! `*_ankle_pitch_link`, and canonical order (which lists pitch before roll,
//! matching the G1 convention) deliberately differs from chain order.

use super::{JointSpec, RobotSpec, NUM_JOINTS};

/// Canonical policy joint order (see module docs).
pub const JOINT_NAMES: [&str; NUM_JOINTS] = [
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
];

/// Per-joint spec. `pos_limit` is per-JOINT (hip/ankle roll ranges are
/// left/right-asymmetric), everything else per-family.
const fn joint(name: &'static str, default_pos: f32, pos_limit: (f32, f32)) -> JointSpec {
    // (kp, kd, effort, vel, armature) per family — see module docs.
    let (kp, kd, effort, vel, armature) = if contains(name, "hip") {
        (240.0, 3.0, 360.0, 20.0, 0.05)
    } else if contains(name, "knee") {
        (360.0, 6.0, 360.0, 20.0, 0.05)
    } else if contains(name, "ankle_pitch") {
        (60.0, 3.0, 66.88, 28.61, 0.01)
    } else {
        // ankle_roll: tiny 19 N·m motor — keep the gentle G1 ankle gain (see
        // module docs).
        (40.0, 2.0, 19.0, 100.7, 0.01)
    };
    JointSpec {
        name,
        kp,
        kd,
        effort_limit: effort,
        vel_limit: vel,
        action_scale: 0.25,
        default_pos,
        pos_limit,
        armature,
        damping: 0.001,
        frictionloss: 0.0,
    }
}

/// `const`-friendly substring search (ASCII).
const fn contains(s: &str, needle: &str) -> bool {
    let (s, n) = (s.as_bytes(), needle.as_bytes());
    if n.len() > s.len() {
        return false;
    }
    let mut i = 0;
    while i + n.len() <= s.len() {
        let mut j = 0;
        while j < n.len() && s[i + j] == n[j] {
            j += 1;
        }
        if j == n.len() {
            return true;
        }
        i += 1;
    }
    false
}

/// The Unitree H2 Plus (legs-only, 12 DOF) spec.
pub const fn unitree_h2_plus() -> RobotSpec {
    let joints = [
        joint(JOINT_NAMES[0], -0.1, (-2.4525975, 2.7754225)), // left_hip_pitch
        joint(JOINT_NAMES[1], 0.0, (-0.467441, 2.1688605)),   // left_hip_roll
        joint(JOINT_NAMES[2], 0.0, (-2.827, 2.827)),          // left_hip_yaw
        joint(JOINT_NAMES[3], 0.3, (-0.08725, 2.53025)),      // left_knee
        joint(JOINT_NAMES[4], -0.2, (-1.13446401, 0.61086524)), // left_ankle_pitch
        joint(JOINT_NAMES[5], 0.0, (-0.34906585, 0.29670597)), // left_ankle_roll
        joint(JOINT_NAMES[6], -0.1, (-2.4525975, 2.7754225)), // right_hip_pitch
        joint(JOINT_NAMES[7], 0.0, (-2.1688605, 0.467441)),   // right_hip_roll (mirrored)
        joint(JOINT_NAMES[8], 0.0, (-2.827, 2.827)),          // right_hip_yaw
        joint(JOINT_NAMES[9], 0.3, (-0.08725, 2.53025)),      // right_knee
        joint(JOINT_NAMES[10], -0.2, (-1.13446401, 0.61086524)), // right_ankle_pitch
        joint(JOINT_NAMES[11], 0.0, (-0.29670597, 0.34906585)), // right_ankle_roll (mirrored)
    ];
    RobotSpec {
        name: "unitree_h2_plus",
        joints,
        base_link: "pelvis",
        // H2 chain: knee → ankle_roll → ankle_pitch; the ankle_pitch link IS
        // the foot (it carries the sole collision capsules).
        foot_links: ["left_ankle_pitch_link", "right_ankle_pitch_link"],
        // Normalizing the ankle-pitch hinge (Y) to +Z leaves the foot's
        // forward axis at +X.
        foot_forward_local: [1.0, 0.0, 0.0],
        foot_contact_z: 0.07, // foot origin sits 0.054 m above the sole
        base_height: 1.032,   // converter FK at the home pose
        spawn_z: 1.039,       // converter FK: straight-leg sole-on-ground
        min_base_height: 0.58,
        total_mass: 77.24,
        mjcf_rel_path: "Documents/work/zealot/assets/robots/unitree_h2_plus_12dof.xml",
        urdf_rel_path: "Documents/work/unitree_ros/robots/h2_plus/H2_Plus.urdf",
        mirror: [6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5],
        mirror_sign: [1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0],
        hip_yawroll: [1, 2, 7, 8], // left/right hip_roll + hip_yaw
        // Only the feet may touch the ground. "ankle" is excluded: the H2's
        // ankle_ROLL link is a small clevis just above the foot, legitimately low.
        illegal_ground_fragments: &["hip", "knee"],
        self_collision_pairs: &[
            ("right_ankle_pitch_link", "left_ankle_pitch_link"),
            ("right_knee_link", "left_knee_link"),
            ("right_hip_yaw_link", "left_hip_yaw_link"),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ankle_roll_is_fragile() {
        let r = unitree_h2_plus();
        let by = |name: &str| r.joints.iter().find(|j| j.name == name).copied().unwrap();
        assert_eq!(by("left_ankle_roll_joint").effort_limit, 19.0);
        assert_eq!(by("left_ankle_roll_joint").kp, 40.0);
        assert_eq!(by("right_knee_joint").effort_limit, 360.0);
        assert_eq!(by("right_hip_pitch_joint").kp, 240.0);
    }

    #[test]
    fn asymmetric_roll_ranges_mirror() {
        let r = unitree_h2_plus();
        assert_eq!(r.joints[1].pos_limit, (-0.467441, 2.1688605));
        assert_eq!(r.joints[7].pos_limit, (-2.1688605, 0.467441));
        assert_eq!(r.joints[5].pos_limit, (-0.34906585, 0.29670597));
        assert_eq!(r.joints[11].pos_limit, (-0.29670597, 0.34906585));
    }
}
