#!/usr/bin/env python3
"""Pull WBC-AGILE's G1 actuator parametrization into a Rust const table.

Parses the `legs` + `feet` DelayedDCMotorCfg blocks in AGILE's
`agile/rl_env/assets/robots/unitree_g1.py` (literal dicts, no isaaclab import
needed), the action scale from the G1 velocity task cfg, and the init-state
joint offsets — then resolves them onto zealot's 12 canonical G1 joints and
writes `zealot-env/tests/data/agile_g1_actuators.rs`, which the
`agile_actuator_parity` unit test `include!`s.

Re-run whenever the WBC-AGILE checkout updates:
  python3 tools/pull_agile_actuators.py [path-to-WBC-AGILE]
"""
import re
import sys
from pathlib import Path

AGILE = Path(sys.argv[1] if len(sys.argv) > 1 else Path.home() / "WBC-AGILE")
robot_py = (AGILE / "agile/rl_env/assets/robots/unitree_g1.py").read_text()
task_py = (
    AGILE / "agile/rl_env/tasks/locomotion/g1/velocity_history_env_cfg.py"
).read_text()

# --- carve out the G1_29DOF_DELAYED_DC_MOTOR block, then its legs/feet groups
m = re.search(r"G1_29DOF_DELAYED_DC_MOTOR = ArticulationCfg\((.*?)\n\)", robot_py, re.S)
assert m, "G1_29DOF_DELAYED_DC_MOTOR not found"
block = m.group(1)

def group(name):
    g = re.search(rf'"{name}": DelayedDCMotorCfg\((.*?)\n        \)', block, re.S)
    assert g, f"actuator group {name} not found"
    return g.group(1)

def parse_dict(text, field):
    """Parse `field={ "regex": value, ... }` or scalar `field=value`."""
    d = re.search(rf"{field}=\{{(.*?)\}}", text, re.S)
    if d:
        return {
            k: float(v)
            for k, v in re.findall(r'"([^"]+)":\s*([0-9.]+)', d.group(1))
        }
    s = re.search(rf"{field}=([0-9.]+)", text)
    return float(s.group(1)) if s else None

legs, feet = group("legs"), group("feet")

def resolve(joint, field):
    """Match zealot's canonical joint name against the group's regex keys."""
    src = feet if "ankle" in joint else legs
    v = parse_dict(src, field)
    if isinstance(v, float) or v is None:
        return v
    for pat, val in v.items():
        if re.fullmatch(pat, joint):
            return val
    raise KeyError(f"{joint}: no {field} pattern matched")

# action scale from the task's JointPositionActionCfg
scale = float(re.search(r"joint_pos = mdp\.JointPositionActionCfg\(.*?scale=([0-9.]+)", task_py, re.S).group(1))

# init-state joint offsets
init = dict(
    re.findall(r'"(\.\*_[a-z_]+_joint)":\s*(-?[0-9.]+)', re.search(r"joint_pos=\{(.*?)\}", block, re.S).group(1))
)
def default_pos(joint):
    for pat, val in init.items():
        if re.fullmatch(pat, joint):
            return float(val)
    return 0.0

CANONICAL = [
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint",
    "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",
    "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
]

rows = []
for j in CANONICAL:
    rows.append(
        (
            j,
            resolve(j, "stiffness"),
            resolve(j, "damping"),
            resolve(j, "effort_limit_sim"),
            resolve(j, "velocity_limit_sim"),
            resolve(j, "armature"),
            resolve(j, "saturation_effort"),
            default_pos(j),
        )
    )

out = Path(__file__).resolve().parent.parent / "zealot-env/tests/data/agile_g1_actuators.rs"
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, "w") as f:
    f.write("// GENERATED by tools/pull_agile_actuators.py — do not edit.\n")
    f.write(f"// Source: WBC-AGILE G1_29DOF_DELAYED_DC_MOTOR + Velocity-G1-History task cfg.\n")
    f.write("// (name, kp, kd, effort, vel_limit, armature, saturation_effort, default_pos)\n")
    f.write(f"pub const AGILE_ACTION_SCALE: f32 = {scale};\n")
    f.write("pub const AGILE_G1_ACTUATORS: [(&str, f32, f32, f32, f32, f32, f32, f32); 12] = [\n")
    for r in rows:
        f.write(f'    ("{r[0]}", {r[1]}, {r[2]}, {r[3]}, {r[4]}, {r[5]}, {r[6]}, {r[7]}),\n')
    f.write("];\n")
print(f"wrote {out}")
for r in rows:
    print(f"  {r[0]:28s} kp={r[1]:<6} kd={r[2]:<4} eff={r[3]:<6} vel={r[4]:<4} arm={r[5]} sat={r[6]} q0={r[7]}")
print(f"  action_scale={scale}")
